-- ตาราง Vacation Leave Requests (VLR) - คำขออนุมัติลาพักร้อน
CREATE TABLE IF NOT EXISTS `vacation_leave_requests` (
  `vlrID` int NOT NULL AUTO_INCREMENT,
  `vlrNo` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `requestDate` date DEFAULT NULL,
  `employeeName` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `department` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `branch` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `leaveType` enum('annual_leave','personal_leave','sick_leave','other') COLLATE utf8mb4_unicode_ci DEFAULT 'annual_leave',
  `startDate` date NOT NULL,
  `endDate` date NOT NULL,
  `totalDays` int DEFAULT 0,
  `reason` text COLLATE utf8mb4_unicode_ci,
  `contactPhone` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `backupPerson` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `approver` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('pending','approved','rejected','cancelled') COLLATE utf8mb4_unicode_ci DEFAULT 'pending',
  `approved_by` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_by` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`vlrID`),
  UNIQUE KEY `vlrNo` (`vlrNo`),
  KEY `idx_employee_id` (`employeeId`),
  KEY `idx_department` (`department`),
  KEY `idx_status` (`status`),
  KEY `idx_start_end` (`startDate`, `endDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
