CREATE TABLE IF NOT EXISTS `kr_shipment_updates` (
  `id` VARCHAR(50) NOT NULL PRIMARY KEY,
  `shipmentNumber` VARCHAR(50) NOT NULL,
  `orderNumber` VARCHAR(50) NOT NULL,
  `destination` ENUM('Korea','Brunei','Thailand','Vietnam') NOT NULL DEFAULT 'Korea',
  `destCode` ENUM('KR','BN','TH','VN') NOT NULL DEFAULT 'KR',
  `shipmentMethod` ENUM('land','sea','air') NOT NULL DEFAULT 'sea',
  `currentStatus` ENUM('preparing','in-transit','customs','delivered') NOT NULL DEFAULT 'preparing',
  `currentLocation` VARCHAR(255) DEFAULT NULL,
  `estimatedDelivery` DATE DEFAULT NULL,
  `trackingNumber` VARCHAR(100) DEFAULT NULL,
  `carrier` VARCHAR(150) DEFAULT NULL,
  `lastUpdate` DATETIME DEFAULT NULL,
  `destinationAddress` TEXT DEFAULT NULL,
  `contactPerson` VARCHAR(150) DEFAULT NULL,
  `contactPhone` VARCHAR(100) DEFAULT NULL,
  `packagingNote` TEXT DEFAULT NULL,
  `totalWeight` VARCHAR(50) DEFAULT NULL,
  `totalBoxes` INT NOT NULL DEFAULT 0,
  `items` JSON DEFAULT NULL,
  `updates` JSON DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_kr_shipment_updates_shipment_number` (`shipmentNumber`),
  KEY `idx_kr_shipment_updates_order_number` (`orderNumber`),
  KEY `idx_kr_shipment_updates_status` (`currentStatus`),
  KEY `idx_kr_shipment_updates_destination` (`destCode`),
  KEY `idx_kr_shipment_updates_estimated_delivery` (`estimatedDelivery`),
  CONSTRAINT `chk_kr_shipment_updates_items_json` CHECK (json_valid(`items`)),
  CONSTRAINT `chk_kr_shipment_updates_updates_json` CHECK (json_valid(`updates`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
