export type SeedChartAccount = {
  code: string
  name_th: string
  name_en: string
  account_type: 'asset' | 'liability' | 'equity' | 'income' | 'expense'
  sub_type?: string
  parent_code?: string | null
  account_alias?: string
  is_sub_account?: number
  department_split?: string
}

export const DEFAULT_CHART_OF_ACCOUNTS: SeedChartAccount[] = [
  { code: '1000-00', name_th: 'สินทรัพย์', name_en: 'Assets', account_type: 'asset', account_alias: '1 กลุ่มสินทรัพย์', is_sub_account: 1, department_split: 'N' },
  { code: '1100-00', name_th: 'สินทรัพย์หมุนเวียน', name_en: 'Current Assets', account_type: 'asset', sub_type: 'current', parent_code: '1000-00', account_alias: 'สินทรัพย์หมุนเวียน', is_sub_account: 2, department_split: 'N' },
  { code: '1110-00', name_th: 'เงินสดและรายการเทียบเท่าเงินสด', name_en: 'Cash and Cash Equivalents', account_type: 'asset', sub_type: 'current', parent_code: '1100-00', account_alias: 'เงินสด', is_sub_account: 3, department_split: 'N' },
  { code: '1110-01', name_th: 'เงินสดย่อย', name_en: 'Petty Cash', account_type: 'asset', sub_type: 'current', parent_code: '1110-00', account_alias: 'เงินสด', is_sub_account: 4, department_split: 'N' },
  { code: '1110-02', name_th: 'เงินสดในมือ', name_en: 'Cash on Hand', account_type: 'asset', sub_type: 'current', parent_code: '1110-00', account_alias: 'เงินสด', is_sub_account: 4, department_split: 'N' },
  { code: '1111-00', name_th: 'เงินฝากธนาคาร', name_en: 'Bank Deposits', account_type: 'asset', sub_type: 'current', parent_code: '1100-00', account_alias: 'เงินฝากธนาคาร', is_sub_account: 3, department_split: 'N' },
  { code: '1111-01', name_th: 'เงินฝากออมทรัพย์', name_en: 'Savings Account', account_type: 'asset', sub_type: 'current', parent_code: '1111-00', account_alias: 'ธนาคาร', is_sub_account: 4, department_split: 'N' },
  { code: '1111-02', name_th: 'เงินฝากกระแสรายวัน', name_en: 'Current Account', account_type: 'asset', sub_type: 'current', parent_code: '1111-00', account_alias: 'ธนาคาร', is_sub_account: 4, department_split: 'N' },
  { code: '1120-00', name_th: 'ลูกหนี้การค้า', name_en: 'Trade Accounts Receivable', account_type: 'asset', sub_type: 'current', parent_code: '1100-00', account_alias: 'ลูกหนี้การค้า', is_sub_account: 3, department_split: 'Y' },
  { code: '1121-00', name_th: 'ลูกหนี้การค้าในประเทศ', name_en: 'Domestic Trade Receivables', account_type: 'asset', sub_type: 'current', parent_code: '1120-00', account_alias: 'ลูกหนี้ในประเทศ', is_sub_account: 4, department_split: 'Y' },
  { code: '1122-00', name_th: 'ค่าเผื่อหนี้สงสัยจะสูญ', name_en: 'Allowance for Doubtful Accounts', account_type: 'asset', sub_type: 'current', parent_code: '1120-00', account_alias: 'ค่าเผื่อหนี้สงสัยจะสูญ', is_sub_account: 4, department_split: 'N' },
  { code: '1130-00', name_th: 'ลูกหนี้อื่น', name_en: 'Other Receivables', account_type: 'asset', sub_type: 'current', parent_code: '1100-00', account_alias: 'ลูกหนี้อื่น', is_sub_account: 3, department_split: 'Y' },
  { code: '1131-00', name_th: 'เงินทดรองจ่ายพนักงาน', name_en: 'Employee Advances', account_type: 'asset', sub_type: 'current', parent_code: '1130-00', account_alias: 'เงินทดรองจ่าย', is_sub_account: 4, department_split: 'Y' },
  { code: '1132-00', name_th: 'เงินให้กู้ยืมกรรมการ', name_en: 'Director Loans', account_type: 'asset', sub_type: 'current', parent_code: '1130-00', account_alias: 'เงินให้กู้ยืม', is_sub_account: 4, department_split: 'N' },
  { code: '1140-00', name_th: 'สินค้าคงเหลือ', name_en: 'Inventories', account_type: 'asset', sub_type: 'current', parent_code: '1100-00', account_alias: 'สินค้าคงเหลือ', is_sub_account: 3, department_split: 'Y' },
  { code: '1141-00', name_th: 'วัตถุดิบ', name_en: 'Raw Materials', account_type: 'asset', sub_type: 'current', parent_code: '1140-00', account_alias: 'วัตถุดิบ', is_sub_account: 4, department_split: 'Y' },
  { code: '1142-00', name_th: 'งานระหว่างทำ', name_en: 'Work in Process', account_type: 'asset', sub_type: 'current', parent_code: '1140-00', account_alias: 'งานระหว่างทำ', is_sub_account: 4, department_split: 'Y' },
  { code: '1143-00', name_th: 'สินค้าสำเร็จรูป', name_en: 'Finished Goods', account_type: 'asset', sub_type: 'current', parent_code: '1140-00', account_alias: 'สินค้าสำเร็จรูป', is_sub_account: 4, department_split: 'Y' },
  { code: '1150-00', name_th: 'สินทรัพย์หมุนเวียนอื่น', name_en: 'Other Current Assets', account_type: 'asset', sub_type: 'current', parent_code: '1100-00', account_alias: 'สินทรัพย์หมุนเวียนอื่น', is_sub_account: 3, department_split: 'N' },
  { code: '1151-00', name_th: 'ภาษีซื้อ', name_en: 'Input VAT', account_type: 'asset', sub_type: 'current', parent_code: '1150-00', account_alias: 'ภาษีซื้อ', is_sub_account: 4, department_split: 'N' },
  { code: '1152-00', name_th: 'ค่าใช้จ่ายจ่ายล่วงหน้า', name_en: 'Prepaid Expenses', account_type: 'asset', sub_type: 'current', parent_code: '1150-00', account_alias: 'จ่ายล่วงหน้า', is_sub_account: 4, department_split: 'N' },
  { code: '1153-00', name_th: 'เงินมัดจำและเงินประกัน', name_en: 'Deposits and Guarantees', account_type: 'asset', sub_type: 'current', parent_code: '1150-00', account_alias: 'เงินมัดจำ', is_sub_account: 4, department_split: 'N' },
  { code: '1200-00', name_th: 'สินทรัพย์ไม่หมุนเวียน', name_en: 'Non-current Assets', account_type: 'asset', sub_type: 'non_current', parent_code: '1000-00', account_alias: 'สินทรัพย์ไม่หมุนเวียน', is_sub_account: 2, department_split: 'N' },
  { code: '1210-00', name_th: 'ที่ดิน อาคารและอุปกรณ์', name_en: 'Property Plant and Equipment', account_type: 'asset', sub_type: 'non_current', parent_code: '1200-00', account_alias: 'PPE', is_sub_account: 3, department_split: 'N' },
  { code: '1211-00', name_th: 'ที่ดิน', name_en: 'Land', account_type: 'asset', sub_type: 'non_current', parent_code: '1210-00', account_alias: 'ที่ดิน', is_sub_account: 4, department_split: 'N' },
  { code: '1212-00', name_th: 'อาคาร', name_en: 'Buildings', account_type: 'asset', sub_type: 'non_current', parent_code: '1210-00', account_alias: 'อาคาร', is_sub_account: 4, department_split: 'N' },
  { code: '1213-00', name_th: 'เครื่องจักรและอุปกรณ์', name_en: 'Machinery and Equipment', account_type: 'asset', sub_type: 'non_current', parent_code: '1210-00', account_alias: 'เครื่องจักร', is_sub_account: 4, department_split: 'N' },
  { code: '1214-00', name_th: 'ยานพาหนะ', name_en: 'Vehicles', account_type: 'asset', sub_type: 'non_current', parent_code: '1210-00', account_alias: 'ยานพาหนะ', is_sub_account: 4, department_split: 'N' },
  { code: '1215-00', name_th: 'เครื่องใช้สำนักงาน', name_en: 'Office Equipment', account_type: 'asset', sub_type: 'non_current', parent_code: '1210-00', account_alias: 'สำนักงาน', is_sub_account: 4, department_split: 'N' },
  { code: '1220-00', name_th: 'ค่าเสื่อมราคาสะสม', name_en: 'Accumulated Depreciation', account_type: 'asset', sub_type: 'non_current', parent_code: '1200-00', account_alias: 'ค่าเสื่อมราคาสะสม', is_sub_account: 3, department_split: 'N' },
  { code: '1221-00', name_th: 'ค่าเสื่อมราคาสะสม-อาคาร', name_en: 'Accumulated Depreciation - Buildings', account_type: 'asset', sub_type: 'non_current', parent_code: '1220-00', account_alias: 'ค่าเสื่อมอาคาร', is_sub_account: 4, department_split: 'N' },
  { code: '1222-00', name_th: 'ค่าเสื่อมราคาสะสม-เครื่องจักร', name_en: 'Accumulated Depreciation - Machinery', account_type: 'asset', sub_type: 'non_current', parent_code: '1220-00', account_alias: 'ค่าเสื่อมเครื่องจักร', is_sub_account: 4, department_split: 'N' },
  { code: '1223-00', name_th: 'ค่าเสื่อมราคาสะสม-ยานพาหนะ', name_en: 'Accumulated Depreciation - Vehicles', account_type: 'asset', sub_type: 'non_current', parent_code: '1220-00', account_alias: 'ค่าเสื่อมยานพาหนะ', is_sub_account: 4, department_split: 'N' },
  { code: '1230-00', name_th: 'สินทรัพย์ไม่มีตัวตน', name_en: 'Intangible Assets', account_type: 'asset', sub_type: 'non_current', parent_code: '1200-00', account_alias: 'สินทรัพย์ไม่มีตัวตน', is_sub_account: 3, department_split: 'N' },
  { code: '1231-00', name_th: 'โปรแกรมคอมพิวเตอร์', name_en: 'Computer Software', account_type: 'asset', sub_type: 'non_current', parent_code: '1230-00', account_alias: 'Software', is_sub_account: 4, department_split: 'N' },

  { code: '2000-00', name_th: 'หนี้สิน', name_en: 'Liabilities', account_type: 'liability', account_alias: '2 กลุ่มหนี้สิน', is_sub_account: 1, department_split: 'N' },
  { code: '2100-00', name_th: 'หนี้สินหมุนเวียน', name_en: 'Current Liabilities', account_type: 'liability', sub_type: 'current', parent_code: '2000-00', account_alias: 'หนี้สินหมุนเวียน', is_sub_account: 2, department_split: 'N' },
  { code: '2110-00', name_th: 'เจ้าหนี้การค้า', name_en: 'Trade Accounts Payable', account_type: 'liability', sub_type: 'current', parent_code: '2100-00', account_alias: 'เจ้าหนี้การค้า', is_sub_account: 3, department_split: 'Y' },
  { code: '2111-00', name_th: 'เจ้าหนี้การค้าในประเทศ', name_en: 'Domestic Trade Payables', account_type: 'liability', sub_type: 'current', parent_code: '2110-00', account_alias: 'เจ้าหนี้ในประเทศ', is_sub_account: 4, department_split: 'Y' },
  { code: '2120-00', name_th: 'เจ้าหนี้อื่น', name_en: 'Other Payables', account_type: 'liability', sub_type: 'current', parent_code: '2100-00', account_alias: 'เจ้าหนี้อื่น', is_sub_account: 3, department_split: 'Y' },
  { code: '2121-00', name_th: 'ค่าใช้จ่ายค้างจ่าย', name_en: 'Accrued Expenses', account_type: 'liability', sub_type: 'current', parent_code: '2120-00', account_alias: 'ค้างจ่าย', is_sub_account: 4, department_split: 'Y' },
  { code: '2122-00', name_th: 'เจ้าหนี้พนักงาน', name_en: 'Employee Payables', account_type: 'liability', sub_type: 'current', parent_code: '2120-00', account_alias: 'เจ้าหนี้พนักงาน', is_sub_account: 4, department_split: 'Y' },
  { code: '2130-00', name_th: 'ภาษีมูลค่าเพิ่มค้างจ่าย', name_en: 'VAT Payable', account_type: 'liability', sub_type: 'current', parent_code: '2100-00', account_alias: 'VAT ค้างจ่าย', is_sub_account: 3, department_split: 'N' },
  { code: '2131-00', name_th: 'ภาษีขาย', name_en: 'Output VAT', account_type: 'liability', sub_type: 'current', parent_code: '2130-00', account_alias: 'ภาษีขาย', is_sub_account: 4, department_split: 'N' },
  { code: '2132-00', name_th: 'ภาษีหัก ณ ที่จ่ายค้างจ่าย', name_en: 'Withholding Tax Payable', account_type: 'liability', sub_type: 'current', parent_code: '2130-00', account_alias: 'WHT ค้างจ่าย', is_sub_account: 4, department_split: 'N' },
  { code: '2140-00', name_th: 'เงินกู้ยืมระยะสั้น', name_en: 'Short-term Loans', account_type: 'liability', sub_type: 'current', parent_code: '2100-00', account_alias: 'เงินกู้ระยะสั้น', is_sub_account: 3, department_split: 'N' },
  { code: '2200-00', name_th: 'หนี้สินไม่หมุนเวียน', name_en: 'Non-current Liabilities', account_type: 'liability', sub_type: 'non_current', parent_code: '2000-00', account_alias: 'หนี้สินไม่หมุนเวียน', is_sub_account: 2, department_split: 'N' },
  { code: '2210-00', name_th: 'เงินกู้ยืมระยะยาว', name_en: 'Long-term Loans', account_type: 'liability', sub_type: 'non_current', parent_code: '2200-00', account_alias: 'เงินกู้ระยะยาว', is_sub_account: 3, department_split: 'N' },
  { code: '2220-00', name_th: 'ประมาณการหนี้สินระยะยาว', name_en: 'Long-term Provisions', account_type: 'liability', sub_type: 'non_current', parent_code: '2200-00', account_alias: 'ประมาณการหนี้สิน', is_sub_account: 3, department_split: 'N' },

  { code: '3000-00', name_th: 'ส่วนของผู้ถือหุ้น', name_en: 'Equity', account_type: 'equity', account_alias: '3 กลุ่มทุน', is_sub_account: 1, department_split: 'N' },
  { code: '3100-00', name_th: 'ทุนจดทะเบียน', name_en: 'Registered Capital', account_type: 'equity', sub_type: 'equity', parent_code: '3000-00', account_alias: 'ทุน', is_sub_account: 2, department_split: 'N' },
  { code: '3101-00', name_th: 'ทุนชำระแล้ว', name_en: 'Paid-up Capital', account_type: 'equity', sub_type: 'equity', parent_code: '3100-00', account_alias: 'ทุนชำระแล้ว', is_sub_account: 3, department_split: 'N' },
  { code: '3200-00', name_th: 'กำไรสะสม', name_en: 'Retained Earnings', account_type: 'equity', sub_type: 'equity', parent_code: '3000-00', account_alias: 'กำไรสะสม', is_sub_account: 2, department_split: 'N' },
  { code: '3300-00', name_th: 'กำไร(ขาดทุน)สุทธิประจำปี', name_en: 'Current Year Net Profit or Loss', account_type: 'equity', sub_type: 'equity', parent_code: '3000-00', account_alias: 'กำไรขาดทุนสุทธิ', is_sub_account: 2, department_split: 'N' },

  { code: '4000-00', name_th: 'รายได้', name_en: 'Income', account_type: 'income', account_alias: '4 กลุ่มรายได้', is_sub_account: 1, department_split: 'N' },
  { code: '4100-00', name_th: 'รายได้จากการขาย', name_en: 'Sales Revenue', account_type: 'income', sub_type: 'revenue', parent_code: '4000-00', account_alias: 'รายได้ขาย', is_sub_account: 2, department_split: 'Y' },
  { code: '4101-00', name_th: 'รายได้จากการขายสินค้า', name_en: 'Product Sales Revenue', account_type: 'income', sub_type: 'revenue', parent_code: '4100-00', account_alias: 'ขายสินค้า', is_sub_account: 3, department_split: 'Y' },
  { code: '4102-00', name_th: 'รายได้จากการให้บริการ', name_en: 'Service Revenue', account_type: 'income', sub_type: 'revenue', parent_code: '4100-00', account_alias: 'บริการ', is_sub_account: 3, department_split: 'Y' },
  { code: '4103-00', name_th: 'รายได้จากการติดตั้ง', name_en: 'Installation Revenue', account_type: 'income', sub_type: 'revenue', parent_code: '4100-00', account_alias: 'ติดตั้ง', is_sub_account: 3, department_split: 'Y' },
  { code: '4200-00', name_th: 'รายได้อื่น', name_en: 'Other Income', account_type: 'income', sub_type: 'other', parent_code: '4000-00', account_alias: 'รายได้อื่น', is_sub_account: 2, department_split: 'N' },
  { code: '4201-00', name_th: 'ดอกเบี้ยรับ', name_en: 'Interest Income', account_type: 'income', sub_type: 'other', parent_code: '4200-00', account_alias: 'ดอกเบี้ยรับ', is_sub_account: 3, department_split: 'N' },
  { code: '4202-00', name_th: 'กำไรจากอัตราแลกเปลี่ยน', name_en: 'Foreign Exchange Gain', account_type: 'income', sub_type: 'other', parent_code: '4200-00', account_alias: 'กำไร FX', is_sub_account: 3, department_split: 'N' },
  { code: '4203-00', name_th: 'รายได้เบ็ดเตล็ด', name_en: 'Miscellaneous Income', account_type: 'income', sub_type: 'other', parent_code: '4200-00', account_alias: 'เบ็ดเตล็ด', is_sub_account: 3, department_split: 'N' },

  { code: '5000-00', name_th: 'ค่าใช้จ่าย', name_en: 'Expenses', account_type: 'expense', account_alias: '5 กลุ่มค่าใช้จ่าย', is_sub_account: 1, department_split: 'N' },
  { code: '5100-00', name_th: 'ต้นทุนขาย', name_en: 'Cost of Sales', account_type: 'expense', sub_type: 'cogs', parent_code: '5000-00', account_alias: 'ต้นทุนขาย', is_sub_account: 2, department_split: 'Y' },
  { code: '5101-00', name_th: 'ต้นทุนสินค้าขาย', name_en: 'Cost of Goods Sold', account_type: 'expense', sub_type: 'cogs', parent_code: '5100-00', account_alias: 'COGS', is_sub_account: 3, department_split: 'Y' },
  { code: '5102-00', name_th: 'ต้นทุนงานติดตั้ง', name_en: 'Installation Cost', account_type: 'expense', sub_type: 'cogs', parent_code: '5100-00', account_alias: 'ต้นทุนติดตั้ง', is_sub_account: 3, department_split: 'Y' },
  { code: '5200-00', name_th: 'ค่าใช้จ่ายในการขาย', name_en: 'Selling Expenses', account_type: 'expense', sub_type: 'operating', parent_code: '5000-00', account_alias: 'ค่าใช้จ่ายขาย', is_sub_account: 2, department_split: 'Y' },
  { code: '5201-00', name_th: 'เงินเดือนฝ่ายขาย', name_en: 'Sales Salaries', account_type: 'expense', sub_type: 'operating', parent_code: '5200-00', account_alias: 'เงินเดือนฝ่ายขาย', is_sub_account: 3, department_split: 'Y' },
  { code: '5202-00', name_th: 'ค่าเดินทางฝ่ายขาย', name_en: 'Sales Travel Expenses', account_type: 'expense', sub_type: 'operating', parent_code: '5200-00', account_alias: 'เดินทางฝ่ายขาย', is_sub_account: 3, department_split: 'Y' },
  { code: '5203-00', name_th: 'ค่าโฆษณาและส่งเสริมการขาย', name_en: 'Advertising and Promotion', account_type: 'expense', sub_type: 'operating', parent_code: '5200-00', account_alias: 'โฆษณา', is_sub_account: 3, department_split: 'Y' },
  { code: '5204-00', name_th: 'ค่าคอมมิชชั่น', name_en: 'Commission Expense', account_type: 'expense', sub_type: 'operating', parent_code: '5200-00', account_alias: 'คอมมิชชั่น', is_sub_account: 3, department_split: 'Y' },
  { code: '5300-00', name_th: 'ค่าใช้จ่ายในการบริหาร', name_en: 'Administrative Expenses', account_type: 'expense', sub_type: 'operating', parent_code: '5000-00', account_alias: 'ค่าใช้จ่ายบริหาร', is_sub_account: 2, department_split: 'Y' },
  { code: '5301-00', name_th: 'เงินเดือนพนักงานสำนักงาน', name_en: 'Office Salaries', account_type: 'expense', sub_type: 'operating', parent_code: '5300-00', account_alias: 'เงินเดือนสำนักงาน', is_sub_account: 3, department_split: 'Y' },
  { code: '5302-00', name_th: 'ค่าเช่าสำนักงาน', name_en: 'Office Rent', account_type: 'expense', sub_type: 'operating', parent_code: '5300-00', account_alias: 'ค่าเช่า', is_sub_account: 3, department_split: 'N' },
  { code: '5303-00', name_th: 'ค่าสาธารณูปโภค', name_en: 'Utilities', account_type: 'expense', sub_type: 'operating', parent_code: '5300-00', account_alias: 'ค่าน้ำไฟ', is_sub_account: 3, department_split: 'N' },
  { code: '5304-00', name_th: 'ค่าใช้จ่ายสำนักงาน', name_en: 'Office Supplies Expense', account_type: 'expense', sub_type: 'operating', parent_code: '5300-00', account_alias: 'อุปกรณ์สำนักงาน', is_sub_account: 3, department_split: 'Y' },
  { code: '5305-00', name_th: 'ค่าเสื่อมราคา', name_en: 'Depreciation Expense', account_type: 'expense', sub_type: 'operating', parent_code: '5300-00', account_alias: 'ค่าเสื่อม', is_sub_account: 3, department_split: 'N' },
  { code: '5306-00', name_th: 'ค่าซ่อมแซมและบำรุงรักษา', name_en: 'Repairs and Maintenance', account_type: 'expense', sub_type: 'operating', parent_code: '5300-00', account_alias: 'ซ่อมบำรุง', is_sub_account: 3, department_split: 'Y' },
  { code: '5307-00', name_th: 'ค่าบริการวิชาชีพ', name_en: 'Professional Fees', account_type: 'expense', sub_type: 'operating', parent_code: '5300-00', account_alias: 'ค่าที่ปรึกษา', is_sub_account: 3, department_split: 'N' },
  { code: '5400-00', name_th: 'ค่าใช้จ่ายทางการเงิน', name_en: 'Financial Expenses', account_type: 'expense', sub_type: 'finance', parent_code: '5000-00', account_alias: 'ค่าใช้จ่ายการเงิน', is_sub_account: 2, department_split: 'N' },
  { code: '5401-00', name_th: 'ดอกเบี้ยจ่าย', name_en: 'Interest Expense', account_type: 'expense', sub_type: 'finance', parent_code: '5400-00', account_alias: 'ดอกเบี้ยจ่าย', is_sub_account: 3, department_split: 'N' },
  { code: '5402-00', name_th: 'ขาดทุนจากอัตราแลกเปลี่ยน', name_en: 'Foreign Exchange Loss', account_type: 'expense', sub_type: 'finance', parent_code: '5400-00', account_alias: 'ขาดทุน FX', is_sub_account: 3, department_split: 'N' },
  { code: '5500-00', name_th: 'ค่าใช้จ่ายภาษี', name_en: 'Tax Expenses', account_type: 'expense', sub_type: 'tax', parent_code: '5000-00', account_alias: 'ภาษี', is_sub_account: 2, department_split: 'N' },
  { code: '5501-00', name_th: 'ภาษีเงินได้นิติบุคคล', name_en: 'Corporate Income Tax', account_type: 'expense', sub_type: 'tax', parent_code: '5500-00', account_alias: 'ภาษีเงินได้', is_sub_account: 3, department_split: 'N' },
  { code: '5502-00', name_th: 'เบี้ยปรับและเงินเพิ่ม', name_en: 'Penalties and Surcharges', account_type: 'expense', sub_type: 'tax', parent_code: '5500-00', account_alias: 'เบี้ยปรับ', is_sub_account: 3, department_split: 'N' },

  { code: '6000-00', name_th: 'บัญชีปิด', name_en: 'Closing Account', account_type: 'equity', sub_type: 'closing', account_alias: 'ปิดบัญชี', is_sub_account: 1, department_split: 'N' },
]
